# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from django.utils.translation import gettext_lazy as _

help_texts = {
    'lino_cosi.lib.orders.Plugin' : _("""See lino.core.plugin.Plugin."""),
}
